### ISSUE TITLE
Description of arguments

### ISSUE THREAD

**Issue by hannasoderstrom1** [JensLidman/chemex2grace#2]
There is no description about the arguments to the scripts, like what is the "reference peaklist"?

**Comment by alvaralmstedt** [comment]
Running as described in README.md does not work. No description of what arguments are needed or what they are

```
(python_course) edu22159:chemex2grace alvaralmstedt$ python main.py
None
Loading data from data dir

DataFiles included:
 ----------------------------------
 ----------------------------------

No data found
```

What is name and peakslist?

**Comment by alvaralmstedt** [comment]
Tested the script again. Now works. Good job!! :)
